# Build this container from its current directory:
#   podman build --build-arg NJOBS=6 -t warpx-perlmutter .
# Adjust NJOBS to the number of processes to use for parallel compilation.
#
# WarpX executables are installed in /usr/bin/
# WarpX Python bindings are installed in /opt/venv
#
# On Perlmutter, run WarpX like this:
#   podman run --rm --gpu --mpi --nccl -it warpx-perlmutter warpx.2d inputs_2d
# Prefix this line with "srun ..." in job scripts, as usual:
#   srun --cpu-bind=cores bash -c "
#     export CUDA_VISIBLE_DEVICES=\$((3-SLURM_LOCALID));
#     podman run ... ${INPUTS} ${GPU_AWARE_MPI}" \
#   > output.txt
#

# Base System and Essential Tools Installation
FROM nvidia/cuda:12.4.1-devel-ubuntu22.04 AS warpx-dev

# WarpX version
ARG warpx_version=25.11

# Build parallelism
ARG NJOBS
ENV NJOBS=$NJOBS

# Perlmutter GPU: A100
# Perlmutter CPU: Zen v3
ENV AMREX_CUDA_ARCH=8.0        \
    CUDAARCHS=80

# Ubuntu apt global options
ENV DEBIAN_FRONTEND=noninteractive

# CMake global options
ENV CMAKE_GENERATOR="Ninja"

# Autotools global options
ENV FORCE_UNSAFE_CONFIGURE=1

# Pip global options
ENV PYTHONDONTWRITEBYTECODE=1

# Custom install location
ENV PATH="/opt/warpx/bin:${PATH}"
ENV LD_LIBRARY_PATH="/opt/warpx/lib:${LD_LIBRARY_PATH}"
ENV CMAKE_PREFIX_PATH="/opt/warpx:${CMAKE_PREFIX_PATH}"

# Install essential system dependencies (development)
# Perlmutter MPICH: cray-mpich/8.1.30 based on MPICH 3.4a2
# Ubuntu 22.04 ships MPICH 4.0, so we build from source
RUN apt-get update           && \
    apt-get install             \
        -y                      \
        --no-install-recommends \
        autoconf                \
        build-essential         \
        ca-certificates         \
        cmake                   \
        coreutils               \
        curl                    \
        g++                     \
        git                     \
        pkg-config           && \
    rm -rf /var/lib/apt/lists/*

# Install MPICH 3.4 w/ GPUdirect support from source
#   after https://docs.nersc.gov/development/containers/shifter/how-to-use/#using-mpi-in-shifter
# Perlmutter MPICH: cray-mpich/8.1.30 based on MPICH 3.4a2
# TODO: install libfabric from source and depend on it (or expose where embedded libfabric gets installed)
ARG mpich=3.4.3
ARG mpich_prefix=mpich-$mpich

RUN \
    curl -Lo $mpich_prefix.tar.gz https://www.mpich.org/static/downloads/$mpich/$mpich_prefix.tar.gz && \
    tar xzf $mpich_prefix.tar.gz                                            && \
    cd $mpich_prefix                                                        && \
    FFLAGS=-fallow-argument-mismatch FCFLAGS=-fallow-argument-mismatch         \
      ./configure                                                              \
        --disable-fortran                                                      \
        --prefix=/opt/warpx                                                    \
        --with-device=ch4:ofi                                               && \
    make -j ${NJOBS}                                                        && \
    make install                                                            && \
    make clean                                                              && \
    cd ..                                                                   && \
    rm -rf ${mpich_prefix}*

RUN /sbin/ldconfig
ENV MPICH_GPU_SUPPORT_ENABLED=1

# TODO: if we build cupy ourselves, we can likely shrink
#       the container size

# Optional: PyTorch (can be added on top as well in a warpx-ml container)
#            \
#                      && \
#    uv pip install       \
#        --no-cache-dir                                      \
#        --upgrade                                           \
#        --index-url https://download.pytorch.org/whl/cu126  \
#        torch
#        optimas[all]

# Build WarpX
# TODO: -DWarpX_DIMS="1;2;RCYLINDER;RSPHERE;RZ;3"
# TODO: -DWarpX_QED_TABLE_GEN=ON (needs boost math)
ENV MPICH_CXX /usr/local/cuda/bin/nvcc
COPY mpi.cu /opt/mpi.cu
RUN mpicxx -show
RUN ${MPICH_CXX} /opt/mpi.cu -o /usr/bin/mpi_hello           \
    -I/opt/warpx/include -L/opt/warpx/lib -lmpicxx -lmpi  && \
    chmod a+rx /usr/bin/mpi_hello

# Reduce to runtime
FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04 AS warpx

# Install essential system dependencies (runtime)
RUN apt-get update            && \
    apt-get install              \
        -y                       \
        --no-install-recommends  \
        ca-certificates       && \
    rm -rf /var/lib/apt/lists/*

# Copy installed software from previous stage
#   TODO: Check BLAS still works
#   TODO: Check this does not copy CUDA devel packages
COPY --from=warpx-dev /opt/warpx /opt/warpx
COPY --from=warpx-dev /usr/bin /usr/bin

# Set up entrypoint
COPY entrypoint.sh /opt/entrypoint.sh
RUN chmod +x /opt/entrypoint.sh
ENTRYPOINT ["/opt/entrypoint.sh"]

# Default command
CMD ["/bin/bash", "-l"]
